"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# :Flavor {{{
#
[flavor]
# dark = "tokyonight-moon"
dark = "tokyo-night"
# dark = "tokyonight-moon"
# [indicator]
# current = { reversed = true }
# preview = { underline = true }
#dark = "dracula"

# }}}

#vim:fileencoding=utf-8:foldmethod=marker
