"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# :Flavor {{{
#
# [flavor]
# dark = "catppuccin-mocha"
# [indicator]
# current = { reversed = true }
# preview = { underline = true }
#dark = "dracula"

# }}}

#vim:fileencoding=utf-8:foldmethod=marker
