theme = "ChaosCore"
client_id = "184ccf6541ff4b61a3f83c4a8511b4a9"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists} {liked}
{album} • {genres}
{metadata}"""
playback_metadata_fields = ["repeat", "shuffle", "volume", "device"]
notify_timeout_in_secs = 0
tracks_playback_limit = 50
app_refresh_duration_in_ms = 1000
playback_refresh_duration_in_ms = 1000
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
progress_bar_position = "Bottom"
genre_num = 2
cover_img_pixels = 512
cover_img_length = 16
cover_img_width = 8
cover_img_scale = 1.0
cover_image_protocol = "Kitty"
enable_media_control = true
enable_streaming = "Always"
enable_notify = true
enable_cover_image_cache = false
default_device = "arch-asusfx"
notify_streaming_only = false
seek_duration_secs = 5
sort_artist_albums_by_type = false

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[layout]
playback_window_position = "Top"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
# name = "arch-asusfx"
# name = "spotify-player"
device_type = "speaker"
volume = 70
# bitrate = 320
audio_cache = false
normalization = false
autoplay = true
